### ISSUE TITLE
Build error: tudat-bundle/tudatpy/tudatpy/kernel/expose_astro/expose_frame_conversion.cpp:50:67: error: no matching function for call to ‘pybind11::module_::def

### ISSUE THREAD

**Issue by piofel** [tudat-team/tudat-bundle#6] opened 2022-01-13 14:59 UTC
I want to use tudat (i.e., not tudatpy), so I switched tudat to the `develop` branch. Then, when I started to build, the following error occured:

Scanning dependencies of target kernel
[ 89%] Building CXX object tudatpy/tudatpy/CMakeFiles/kernel.dir/kernel/kernel.cpp.o
[ 89%] Building CXX object tudatpy/tudatpy/CMakeFiles/kernel.dir/kernel/expose_astro.cpp.o
[ 89%] Building CXX object tudatpy/tudatpy/CMakeFiles/kernel.dir/kernel/expose_astro/expose_gravitation.cpp.o
[ 90%] Building CXX object tudatpy/tudatpy/CMakeFiles/kernel.dir/kernel/expose_astro/expose_element_conversion.cpp.o
[ 90%] Building CXX object tudatpy/tudatpy/CMakeFiles/kernel.dir/kernel/expose_astro/expose_frame_conversion.cpp.o
/home/piotr/cpp_libraries/tudat-bundle/tudatpy/tudatpy/kernel/expose_astro/expose_frame_conversion.cpp: In function ‘void tudatpy::astro::frame_conversion::expose_frame_conversion(pybind11::module&)’:
/home/piotr/cpp_libraries/tudat-bundle/tudatpy/tudatpy/kernel/expose_astro/expose_frame_conversion.cpp:50:67: error: no matching function for call to ‘pybind11::module_::def(const char [32], <unresolved overloaded function type>, pybind11::arg, pybind11::arg_v, const char*)’
   50 |           get_docstring("tnw_to_inertial_rotation_matrix").c_str());
      |                                                                   ^
In file included from /home/piotr/cpp_libraries/tudat-bundle/tudatpy/tudatpy/kernel/expose_astro/expose_frame_conversion.h:14,
                 from /home/piotr/cpp_libraries/tudat-bundle/tudatpy/tudatpy/kernel/expose_astro/expose_frame_conversion.cpp:13:
/home/piotr/anaconda3/envs/tudat-bundle/include/pybind11/pybind11.h:1032:14: note: candidate: ‘template<class Func, class ... Extra> pybind11::module_& pybind11::module_::def(const char*, Func&&, const Extra& ...)’
 1032 |     module_ &def(const char *name_, Func &&f, const Extra& ... extra) {
      |              ^~~
/home/piotr/anaconda3/envs/tudat-bundle/include/pybind11/pybind11.h:1032:14: note:   template argument deduction/substitution failed:
/home/piotr/cpp_libraries/tudat-bundle/tudatpy/tudatpy/kernel/expose_astro/expose_frame_conversion.cpp:50:67: note:   couldn’t deduce template parameter ‘Func’
   50 |           get_docstring("tnw_to_inertial_rotation_matrix").c_str());
      |                                                                   ^
make[2]: *** [tudatpy/tudatpy/CMakeFiles/kernel.dir/build.make:115: tudatpy/tudatpy/CMakeFiles/kernel.dir/kernel/expose_astro/expose_frame_conversion.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1953: tudatpy/tudatpy/CMakeFiles/kernel.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by FilippoOggionni** [comment] 2022-01-13 16:48
Hi @piofel , thanks for posting this.

I am not sure what the error is caused by, but it is caused while exposing tudatpy. If you only need Tudat and not tudatpy, I'd recommend building only the tudat project directly from the `develop` branch of the tudat-team/tudat repo ([link](https://github.com/tudat-team/tudat/tree/develop)), without using necessarily tudat-bundle (which on the contrary builds tudatpy as well).

**Comment by piofel** [comment] 2022-01-14 08:57
Hello @FilippoOggionni, thank you very much for the reply, it will be sufficient for my needs. I will do so.

**Comment by FilippoOggionni** [comment] 2022-01-14 13:02
No problem @piofel ! I will close this, please reopen if you keep having issues.

**Closed as completed by FilippoOggionni** 2022-01-14 13:02 UTC
